'use strict';

/**
 * core/build-worker.js - Worker thread for parallel index building
 *
 * Receives a chunk of file paths, parses each file, extracts symbols and calls,
 * then sends results back to the main thread via MessagePort.
 * Mirrors the indexFile() logic in project.js.
 */

const { workerData } = require('worker_threads');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { detectLanguage, getParser, getLanguageModule, langTraits } = require('../languages');
const { parse } = require('./parser');
const { extractImports, extractExports } = require('./imports');

const { files, rootDir, existingHashes, signal, workerIndex, port } = workerData;
const signalArray = new Int32Array(signal);

function addSymbol(fileEntry, item, type) {
    const symbol = {
        name: item.name,
        type,
        file: fileEntry.path,
        relativePath: fileEntry.relativePath,
        startLine: item.startLine,
        endLine: item.endLine,
        params: item.params,
        paramsStructured: item.paramsStructured,
        returnType: item.returnType,
        modifiers: item.modifiers,
        docstring: item.docstring,
        bindingId: `${fileEntry.relativePath}:${type}:${item.startLine}`,
    };
    if (item.generics) symbol.generics = item.generics;
    if (item.extends) symbol.extends = item.extends;
    if (item.implements) symbol.implements = item.implements;
    if (item.indent !== undefined) symbol.indent = item.indent;
    if (item.isNested) symbol.isNested = item.isNested;
    if (item.isMethod) symbol.isMethod = item.isMethod;
    if (item.receiver) symbol.receiver = item.receiver;
    if (item.className) symbol.className = item.className;
    if (item.memberType) symbol.memberType = item.memberType;
    if (item.fieldType) symbol.fieldType = item.fieldType;
    if (item.decorators && item.decorators.length > 0) symbol.decorators = item.decorators;
    if (item.nameLine) symbol.nameLine = item.nameLine;
    if (item.traitImpl) symbol.traitImpl = true;
    if (item.isSignature) symbol.isSignature = true;

    fileEntry.symbols.push(symbol);
    fileEntry.bindings.push({
        id: symbol.bindingId,
        name: symbol.name,
        type: symbol.type,
        startLine: symbol.startLine,
    });
}

function processFile(filePath) {
    const stat = fs.statSync(filePath);
    const existing = existingHashes[filePath];

    // Fast path: skip when mtime+size both match
    if (existing && existing.mtime === stat.mtimeMs && existing.size === stat.size) {
        return { filePath, skipped: true };
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const hash = crypto.createHash('md5').update(content).digest('hex');

    // Content-based skip: mtime changed but content didn't (touch, git checkout)
    if (existing && existing.hash === hash) {
        return { filePath, skipped: true, mtimeUpdate: stat.mtimeMs, sizeUpdate: stat.size };
    }

    const language = detectLanguage(filePath);
    if (!language) return { filePath, skipped: true };

    // Parse content — safeParse cache ensures tree is shared across
    // parse()/extractImports()/extractExports()/findCallsInCode() (1 parse per file)
    const parsed = parse(content, language);
    const { imports, dynamicCount, importAliases } = extractImports(content, language);
    const { exports } = extractExports(content, language);

    // Extract calls in the same pass (eliminates buildCalleeIndex re-parsing)
    let calls = null;
    const langModule = getLanguageModule(language);
    if (langModule.findCallsInCode) {
        const parser = getParser(language);
        const callOpts = {};
        if (langTraits(language)?.hasReceiverPackageCalls) {
            callOpts.imports = imports.flatMap(i => i.names || []);
        }
        calls = langModule.findCallsInCode(content, parser, callOpts);
    }

    // Detect bundled/minified files (same logic as indexFile in project.js)
    let lineCount = 1, longLineCount = 0, lineStart = 0;
    for (let ci = 0; ci < content.length; ci++) {
        if (content.charCodeAt(ci) === 10) {
            if (ci - lineStart > 1000) longLineCount++;
            lineStart = ci + 1;
            lineCount++;
        }
    }
    if (content.length - lineStart > 1000) longLineCount++;

    const isBundled = (
        content.includes('__webpack_require__') || content.includes('__webpack_modules__') ||
        (lineCount > 0 && lineCount < 50 && content.length / lineCount > 500) ||
        (lineCount > 0 && longLineCount > 0 && longLineCount / lineCount > 0.3)
    );

    const isGenerated = /^\/\/\s*Code generated\b|^\/\/\s*DO NOT EDIT|^\/\/ @generated|^# Generated by/m.test(
        content.slice(0, 500)
    );

    const relativePath = path.relative(rootDir, filePath);

    // Build fileEntry (mirrors indexFile)
    const fileEntry = {
        path: filePath,
        relativePath,
        language,
        lines: lineCount,
        hash,
        mtime: stat.mtimeMs,
        size: stat.size,
        imports: imports.map(i => i.module),
        importNames: imports.flatMap(i => i.names || []),
        exports: exports.map(e => e.name),
        exportDetails: exports,
        symbols: [],
        bindings: [],
        dynamicImports: dynamicCount || 0,
    };
    if (importAliases) fileEntry.importAliases = importAliases;
    if (isBundled) fileEntry.isBundled = true;
    if (isGenerated) fileEntry.isGenerated = true;

    // Build symbols (mirrors indexFile)
    for (const fn of parsed.functions) {
        if (fn.receiver && !fn.className) {
            fn.className = fn.receiver.replace(/^\*/, '');
        }
        addSymbol(fileEntry, fn, fn.isConstructor ? 'constructor' : 'function');
    }

    for (const cls of parsed.classes) {
        addSymbol(fileEntry, cls, cls.type || 'class');
        if (cls.members) {
            for (const m of cls.members) {
                addSymbol(fileEntry, { ...m, className: cls.name, ...(cls.traitName && { traitImpl: true }) }, m.memberType || 'method');
            }
        }
    }

    for (const state of parsed.stateObjects) {
        addSymbol(fileEntry, state, 'state');
    }

    return {
        filePath,
        fileEntry,
        calls,
        callsMtime: stat.mtimeMs,
        callsHash: hash,
        hadExisting: !!existing,
    };
}

// Process all files
try {
    const results = [];
    for (const filePath of files) {
        try {
            results.push(processFile(filePath));
        } catch (e) {
            results.push({ filePath, error: e.message });
        }
    }

    port.postMessage(results);
    port.close();
    Atomics.store(signalArray, workerIndex, 1);
    Atomics.notify(signalArray, workerIndex);
} catch (e) {
    // Worker-level error — signal completion with empty results
    try { port.postMessage([]); port.close(); } catch (_) { /* ignore */ }
    Atomics.store(signalArray, workerIndex, 1);
    Atomics.notify(signalArray, workerIndex);
}
