'use strict';

/**
 * core/build-worker.js - Worker thread for parallel index building
 *
 * Receives a chunk of file paths, parses each file, extracts symbols and calls,
 * then sends results back to the main thread via MessagePort.
 * Mirrors the indexFile() logic in project.js.
 */

const { workerData } = require('worker_threads');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { detectLanguage, getParser, getLanguageAdapter } = require('../languages');
const { validateFileIR } = require('./ir');
const { createFileEntryFromIR, populateFileEntryFromIR } = require('./index-ir');

const { files, rootDir, existingHashes, signal, workerIndex, port } = workerData;
const signalArray = new Int32Array(signal);

function processFile(filePath) {
    const stat = fs.statSync(filePath);
    const existing = existingHashes[filePath];

    // Fast path: skip when mtime+size both match
    if (existing && existing.mtime === stat.mtimeMs && existing.size === stat.size) {
        return { filePath, skipped: true };
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const hash = crypto.createHash('md5').update(content).digest('hex');

    // Content-based skip: mtime changed but content didn't (touch, git checkout)
    if (existing && existing.hash === hash) {
        return { filePath, skipped: true, mtimeUpdate: stat.mtimeMs, sizeUpdate: stat.size };
    }

    const language = detectLanguage(filePath);
    if (!language) return { filePath, skipped: true };

    // One adapter analysis produces the complete, validated file IR consumed
    // by both worker and sequential builds.
    const adapter = getLanguageAdapter(language);
    const parser = getParser(language);
    const ir = adapter.analyze(content, parser, filePath);
    const irFailures = validateFileIR(ir);
    if (irFailures.length > 0) {
        throw new Error(`Invalid ${language} IR: ${irFailures.join('; ')}`);
    }

    // Detect bundled/minified files (same logic as indexFile in project.js)
    let lineCount = 1, longLineCount = 0, lineStart = 0;
    for (let ci = 0; ci < content.length; ci++) {
        if (content.charCodeAt(ci) === 10) {
            if (ci - lineStart > 1000) longLineCount++;
            lineStart = ci + 1;
            lineCount++;
        }
    }
    if (content.length - lineStart > 1000) longLineCount++;
    // A trailing newline TERMINATES the last line rather than opening a new
    // one; an empty file has 0 lines (fix #251 — adjusted in indexFile only,
    // so parallel-built stats reported +1 line per newline-terminated file).
    if (content.length === 0) lineCount = 0;
    else if (content.charCodeAt(content.length - 1) === 10) lineCount--;

    const isBundled = (
        content.includes('__webpack_require__') || content.includes('__webpack_modules__') ||
        (lineCount > 0 && lineCount < 50 && content.length / lineCount > 500) ||
        (lineCount > 0 && longLineCount > 0 && longLineCount / lineCount > 0.3)
    );

    const isGenerated = /^\/\/\s*Code generated\b|^\/\/\s*DO NOT EDIT|^\/\/ @generated|^# Generated by/m.test(
        content.slice(0, 500)
    );

    const relativePath = path.relative(rootDir, filePath);

    const fileEntry = createFileEntryFromIR({
        ir,
        filePath,
        relativePath,
        hash,
        mtime: stat.mtimeMs,
        size: stat.size,
        lineCount,
        isBundled,
        isGenerated,
    });
    populateFileEntryFromIR(fileEntry, ir);

    return {
        filePath,
        fileEntry,
        calls: ir.calls,
        callsMtime: stat.mtimeMs,
        callsHash: hash,
        hadExisting: !!existing,
    };
}

// Process all files
try {
    const results = [];
    for (const filePath of files) {
        try {
            results.push(processFile(filePath));
        } catch (e) {
            results.push({ filePath, error: e.message });
        }
    }

    port.postMessage(results);
    port.close();
    Atomics.store(signalArray, workerIndex, 1);
    Atomics.notify(signalArray, workerIndex);
} catch (e) {
    // Worker-level error — signal completion with empty results
    try { port.postMessage([]); port.close(); } catch (_) { /* ignore */ }
    Atomics.store(signalArray, workerIndex, 1);
    Atomics.notify(signalArray, workerIndex);
}
